language: rust
before_install: |
  sudo apt-get update -qq &&
  sudo apt-get install -y libmecab-dev
after_success: |
  sudo apt-get install -y binutils-dev libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  echo $TRAVIS_JOB_ID &&
  kcov --exclude-pattern=/.cargo --coveralls-id=$TRAVIS_JOB_ID target/kcov target/debug/lib-*
